defmodule AdventOfCodeTest.Y2024.D8Test do
  use ExUnit.Case, async: true

  alias AdventOfCode.Y2024.D8, as: Puzzle

  @antenna_map """
  ............
  ........0...
  .....0......
  .......0....
  ....0.......
  ......A.....
  ............
  ............
  ........A...
  .........A..
  ............
  ............
  """

  test "part 1 examples" do
    assert {14, 34} = Puzzle.run(@antenna_map)
  end

  test "solution" do
    assert {344, 1182} = Puzzle.run()
  end
end
