defmodule AdventOfCodeTest.Y2025.D7Test do
  use ExUnit.Case, async: true

  alias AdventOfCode.Y2025.D7, as: Puzzle

  @manifold """
  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  """

  test "examples" do
    assert {21, 40} = Puzzle.run(@manifold)
  end

  test "solution" do
    assert {1672, 231_229_866_702_355} = Puzzle.run()
  end
end
